/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.dcs.GasBoy;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int default_hdpi_landscape=0x7f020000;
        public static final int default_hdpi_portrait=0x7f020001;
        public static final int default_ldpi_landscape=0x7f020002;
        public static final int default_ldpi_portrait=0x7f020003;
        public static final int default_mdpi_landscape=0x7f020004;
        public static final int default_mdpi_portrait=0x7f020005;
        public static final int default_xhdpi_landscape=0x7f020006;
        public static final int default_xhdpi_portrait=0x7f020007;
        public static final int icon=0x7f020008;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
    }
    public static final class xml {
        public static final int config=0x7f030000;
    }
}
